 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
    name: sample1
 spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: sample1
          tier: backend
      spec: 
        containers:
        - name: sample1
          image: sample1:1.0
          imagePullPolicy: IfNotPresent
          resources: 
            requests:
              cpu: 100m
              memory: 100Mi
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports: 
          - containerPort: 8080
